"use strict";

export const INIT_APP = "INIT_APP";

export const FETCH_APP_DATA = "FETCH_APP_DATA";
export const FETCH_APP_DATA_REJECTED = "FETCH_APP_DATA_REJECTED";
export const FETCH_APP_DATA_PENDING = "FETCH_APP_DATA_PENDING";
export const FETCH_APP_DATA_FULFILLED = "FETCH_APP_DATA_FULFILLED";

export const FETCH_NEWS = "FETCH_NEWS";
export const FETCH_NEWS_REJECTED = "FETCH_NEWS_REJECTED";
export const FETCH_NEWS_PENDING = "FETCH_NEWS_PENDING";
export const FETCH_NEWS_FULFILLED = "FETCH_NEWS_FULFILLED";

export const OPEN_NEWS_ENTRY = "OPEN_NEWS_ENTRY";
export const OPEN_NEWS_ENTRY_REJECTED = "OPEN_NEWS_ENTRY_REJECTED";
export const OPEN_NEWS_ENTRY_PENDING = "OPEN_NEWS_ENTRY_PENDING";
export const OPEN_NEWS_ENTRY_FULFILLED = "OPEN_NEWS_ENTRY_FULFILLED";


export const POST_NEWS_COMMENT = "POST_NEWS_COMMENT";
export const POST_NEWS_COMMENT_REJECTED = "POST_NEWS_COMMENT_REJECTED";
export const POST_NEWS_COMMENT_PENDING = "POST_NEWS_COMMENT_PENDING";
export const POST_NEWS_COMMENT_FULFILLED = "POST_NEWS_COMMENT_FULFILLED";
