export const NEWS_FETCH = "NEWS_FETCH";
export const NEWS_FETCH_PENDING = "NEWS_FETCH_PENDING";
export const NEWS_FETCH_FULFILLED = "NEWS_FETCH_FULFILLED";
export const NEWS_FETCH_REJECTED = "NEWS_FETCH_REJECTED";

export const NEWS_PICK_ENTRY = "NEWS_PICK_ENTRY";

export const NEWS_LOAD_ENTRY = "NEWS_LOAD_ENTRY";
export const NEWS_LOAD_ENTRY_FULFILLED = "NEWS_LOAD_ENTRY_FULFILLED";
export const NEWS_LOAD_ENTRY_REJECTED = "NEWS_LOAD_ENTRY_REJECTED";
export const NEWS_LOAD_ENTRY_PENDING = "NEWS_LOAD_ENTRY_PENDING";
